**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

In [2]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [ ]:
grades = [96, 100, 100, 69, 78, 95, 92, 89, 92, 88,]
grades_array = np.array(grades)
print(grades_array)

[ 96 100 100  69  78  95  92  89]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [ ]:
product_prices = [
    [47, 21, 29, 98], 
    [23, 35, 98, 99], 
    [76, 96, 12, 17]  
]

matrix = np.array(product_prices)
print(matrix)

3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [ ]:
grades = [96, 100, 100, 69, 78, 95, 92, 89, 92, 88]
array = np.array(grades)
print(array)

product_prices = [
    [47, 21, 29, 98], 
    [23, 35, 98, 99], 
    [76, 96, 12, 17]  
]

matrix = np.array(product_prices)
print(matrix)

print(array.dtype)
print(matrix.dtype)

4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [ ]:
grades = [96, 100, 100, 69, 78, 95, 92, 89, 92, 88]
array = np.array(grades)
print(array)

product_prices = [
    [47, 21, 29, 98], 
    [23, 35, 98, 99], 
    [76, 96, 12, 17]  
]

matrix = np.array(product_prices)
print(matrix)

print(array.shape)
print(matrix.shape)

5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [ ]:
days = 7
start_profit = 0
end_profit = 1000.50

profit_array = np.linspace(start_profit, end_profit, days)
print(profit_array)

6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [ ]:
array_one = np.array([[51, 52, 58], [49, 53, 60]])
array_two = np.array([[18, 84, 91], [14, 91, 16]])

horizontical = np.hstack((array_one, array_two))

vertical= np.vstack((array_one, array_two))

print(array_one)
print(array_two)
print(horizontical)
print(vertical)

7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [ ]:
def transp_array(arr):
    return arr.reshape(arr.shape[1], arr.shape[0])
matrix = np.array([[10, 27, 33], [41, 57, 64]])
transp_matrix = transp_array(matrix)

print(matrix)
print(transp_matrix)

8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [ ]:
array_one = np.array([[15, 9], [22, 45]])
array_two = np.array([[57, 61], [77, 9]])

add = array_one + array_two
sub = array_one - array_two
scalar_multip = array_one * 2
element_multip = array_one * array_two
matrix = np.dot(array_one, array_two)

print(array_one)
print(array_two)
print(add)
print(sub)
print(scalar_multip)
print(element_multip)
print(matrix)

[[15  9]
 [22 45]]
[[57 61]
 [77  9]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [11]:
Array = np.array([
    [8, 2, 3],
    [6, 5, 4],
    [2, 3, 1]
])

min = np.min(Array)
max = np.max(Array)
sum = np.sum(Array)
row_min = np.min(Array, axis=1)
colum_max= np.max(Array, axis=0)

print(matrix)
print(min)
print(max)
print(sum)
print(row_min)
print(colum_max)

[[1548  996]
 [4719 1747]]
1
8
34
[2 4 1]
[8 5 4]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [12]:
Array = np.array([
    [1, 1, 3],
    [7, 2, 7],
    [3, 2, 1]
])

unique, frequencies = np.unique(Array, return_counts=True)

print(unique)
print(frequencies)

[1 2 3 7]
[3 2 2 2]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [13]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [17]:
dataframe = [
    {'last_name':"Богач",'first_name':  "Іван", 'birth_date':"2012-05-17",'weight': 78.5, 'insurance':True},
    {'last_name':"Сидор",'first_name':  "Назар",'birth_date': "2022-08-25", 'weight':65.0, 'insurance':False},
    {'last_name':"Клим", 'first_name': "Роман", 'birth_date':"2005-11-03", 'weight':79.3, 'insurance':True}, 
    {'last_name':"Оліх", 'first_name': "Анна", 'birth_date':"2006-02-14", 'weight':None, 'insurance':False}
]

df = pd.DataFrame(dataframe)
print(df)
print(df.dtypes)


  last_name first_name  birth_date  weight  insurance
0     Богач       Іван  2012-05-17    78.5       True
1     Сидор      Назар  2022-08-25    65.0      False
2      Клим      Роман  2005-11-03    79.3       True
3      Оліх       Анна  2006-02-14     NaN      False
last_name      object
first_name     object
birth_date     object
weight        float64
insurance        bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [ ]:
df = pd.read_csv('missile_attacks_daily.csv')

print(df.head())
print(df.dtypes)

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [ ]:
df.head(10)

14. Отримайте інформацію про форму датафрейму.

In [ ]:
df.shape()

15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [ ]:
df.info()

16. Отримайте статистику для колонок числового типу.

In [ ]:
df.describe()

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [ ]:
unique = df.nunique()
fewest_unique = unique.idxmin()
counts = df[fewest_unique].counts()

print(fewest_unique)
print(counts)

18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Пункт списку
2.   Пункт списку

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [ ]:
df['launched'] = df['launched'].astype('Int64')

print(df['launched'].dtype)

print(df['launched'].head())

20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [23]:
drop = 0.3 * len(df) 

clean = df.dropna(thresh=drop, axis=1)

print(clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   last_name   4 non-null      object 
 1   first_name  4 non-null      object 
 2   birth_date  4 non-null      object 
 3   weight      3 non-null      float64
 4   insurance   4 non-null      bool   
dtypes: bool(1), float64(1), object(3)
memory usage: 264.0+ bytes
None


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

**місце для текстової відповіді**

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [30]:
df[df.isnull().any(axis=1)]

last_name first_name  birth_date  weight  insurance
3      Оліх       Анна  2006-02-14     NaN      False